---
title: "Intro_gov_sj.rmd"
author: "Shan Jiang"
date: "11/24/2018"
output: github_document
---

## Data: May 2017 National Occupational Employment and Wage Estimates United States>

## Salary Prospect From 2017 
```{r}
library(tidyverse)
```


```{r}
library(readxl)
national_17 <- read_excel("data/oesm17nat/national_M2017_dl.xlsx")


national_17 = national_17 %>% 
              janitor::clean_names() %>% 
              filter(str_detect(occ_code, "^[1][5]") | 
                    occ_title == "All Occupations" | 
                    str_detect(occ_code, "^[1][3]") | 
                    str_detect(occ_code, "^[1][9]")) %>% 
              arrange(desc(tot_emp), a_mean)

## Annual Average comparison for different majors 
national_17 %>% 
              janitor::clean_names() %>% 
              filter(occ_group == "major" | occ_group == "total") %>% 
              mutate(occ_title = as.factor(occ_title)) %>% 
              arrange(desc(tot_emp), a_mean) %>% 
              mutate(CI_salary_low = a_mean - mean_prse, 
                     CI_salary_high = a_mean + mean_prse ) %>% 
  ggplot(aes(occ_title, a_mean)) +
    geom_point() + 
  geom_errorbar(ymax = national_17$a_mean +  national_17$mean_rpse , 
                ymin =  national_17$a_mean -  national_17$mean_rpse) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x = element_text(angle = 90, size = 8),
        legend.key.size = unit(0.05, "cm"))
  
              

national_17 %>% 
filter(occ_code == "13-0000" | 
                    occ_title == "All Occupations" | 
                    occ_code ==  "15-0000" | 
                    occ_code == "19-0000") %>% 
              arrange(desc(tot_emp), a_mean)
  

```

For detetcting the outlook of the computer and math category jobs, we carried out comparison with jobs in some popular fields, such as the 


## Geographical plots and maps 

```{r}




```

