---
title: "read data from Indeed"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(rvest)
library(httr)
library(stringr)
```

### read data (existing)

```{r}
datascience <- read_csv("./data/datascience_market/alldata.csv")

dim(datascience)

head(datascience)

str(datascience)
```

### tidy datascience data

degree

```{r}
datascience %>% 
  filter(str_detect(description, c("[Bb]achelor", "BA", "BS")) == TRUE)

datascience %>% 
  mutate(degree = ifelse(str_detect(.$description,  c("[Bb]achelor", "BA", "BS", "B.S")) == TRUE, "bachelor",
                        ifelse(str_detect(.$description, "[Mm]aster") == TRUE, "master",
                               ifelse(str_detect(.$description, "[Pp][Hh][Dd]") == TRUE, "phd", "other")))) %>% 
  ggplot(aes(x = degree)) + geom_bar()

datascience %>% 
  mutate(degree = ifelse(str_detect(.$description,  c("[Bb]achelor", "BA", "BS", "B.S")) == TRUE, "bachelor",
                        ifelse(str_detect(.$description, "[Mm]aster") == TRUE, "master",
                               ifelse(str_detect(.$description, "[Pp][Hh][Dd]") == TRUE, "phd", "other")))) %>% 
  ggplot(aes(x = degree)) + geom_bar()

datascience %>% 
  filter(str_detect(.$description, "years experience") == TRUE)
```

major:

```{r}
datascience %>% 
  filter(str_detect(description, "[Mm]athematics") == TRUE)

datascience %>% 
  filter(str_detect(description, "[Cc]omputer") == TRUE)

datascience %>% 
   mutate(major.math = ifelse(str_detect(.$description, "[Mm]athematics") == TRUE, "Math", NA))
```









