---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(ggmap)
library(fiftystater)
library(plotly)
library(tidyverse)

library(shiny)
library(readxl)


salary_data %>% 
  janitor::clean_names() %>% 
  mutate(state = tolower(state)) %>%    
  mutate(a_mean = as.numeric(a_mean)) %>%
  mutate(tot_emp = as.numeric(tot_emp)) %>% 
  mutate(a_mean = ifelse(is.na(a_mean), mean(a_mean, na.rm = TRUE), a_mean)) %>% 
  filter(str_detect(occ_code, "^[1][5]") ) %>% 
  filter(!state %in% c("Puerto Rico","Guam", "Virgin Islands")) %>% 
  group_by(state) %>%
  summarize(mean_salary = mean(a_mean))

salary_data <- salary_data %>% 
  mutate(text_label = str_c("Salary: $", mean_salary))   
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
library(shiny)    # for shiny apps
library(leaflet)  # renderLeaflet function

max_salary = 107960 
min_salary =  salary_data %>% 
    distinct(mean_salary) %>% 
    min()

# selectInput widget
  sliderInput(inputId = "Mean annual salary range", label = h3("Select salary range"),
            min_salary, 
            max_salary, 
            value = c(30000, 110000)
  )

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
  ggplotly(
  ggplot( state_salary, aes(map_id = state)) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill =  mean_salary), map = states_map) + 
  expand_limits(x = states_map$long, y = states_map$lat) 
  )
})

```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

