---
title: "treemap"
author: "Guojing Wu"
date: "12/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(d3treeR)
library(treemap)
library(tidyverse)
```

## treemap

```{r}
datascience <- read_csv("./data/ds_500.csv") %>% 
  filter(!is.na(position))
```

```{r}
pattern_bg = c("[Cc]omputer [Ss]cience | \\bC\\.?S\\b | [Mm]achine [Ll]earning | \\bM\\.?L\\b", 
                 "[Ss]tatistic", 
                 "[Mm]ath", 
                 "[Qq]uantitative", 
                 "[Ee]conomic", 
                 "[Bb]iolog", 
                 "[Bb]iostatis", 
                 "[Dd]ata [Ss]cience | \\bD\\.?S\\b", 
                 "[Cc]hemical [Ee]ngineering")
name_bg = c("CS", 
          "Statistics", 
          "Mathematics", 
          "Quantitative", 
          "Economics", 
          "Biology", 
          "Biostatistics", 
          "DS", 
          "Engineer")

bg_freq = data.frame(
  background = pattern_bg, 
  index = name_bg, 
  freq_total = rep(0, length(pattern_bg)), 
  top500 = rep(0, length(pattern_bg)), 
  nontop500 = rep(0, length(pattern_bg)) 
)

for (i in c(1:length(pattern_bg))) {
  bg_freq$freq_total[i] = sum(str_detect(datascience$description, as.character(bg_freq$background[i])))
  bg_freq$top500[i] = sum(str_detect(datascience$description[which(datascience$flag == 1)], as.character(bg_freq$background[i])))
  bg_freq$nontop500[i] = sum(str_detect(datascience$description[which(datascience$flag == 0)], as.character(bg_freq$background[i])))
}

bg_freq = 
  bg_freq %>% 
  gather(key = subgroup, value = freq, top500:nontop500) %>% 
  mutate(freq_ratio = ifelse(subgroup == "top500", freq/sum(datascience$flag == 1), freq/sum(datascience$flag == 0))) %>% 
  mutate(subgroup = paste("In ", subgroup, ": n(companies) = ", freq, ", ratio = ", round(freq_ratio, digits = 3), sep = ""))
  

d3tree(
  treemap(
    bg_freq,
    index = c("index", "subgroup"), 
    vSize = "freq_ratio", 
    vColor = "freq_ratio", 
    type = "value",
    palette = "Blues"
    ),
  rootname = "General"
  )
```
