---
title: "flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(readr)
library(rvest)
library(stringr)
library(tidytext)
library(wordcloud)
library(RColorBrewer)
library(treemap)
library(ggplot2)
library(ggmap)
library(plotly)
library(d3treeR)
library(packcircles)
# devtools::install_github("timelyportfolio/d3treeR")
```

```{r map, message=FALSE, warning=FALSE, include=F}
state_17 <- read_xlsx("./data/state/oesm17st/state_M2017_dl.xlsx") %>% 
  janitor::clean_names() %>% 
  mutate(a_mean = as.numeric(a_mean)) %>%
  mutate(tot_emp = as.numeric(tot_emp))

## Missing data replaced by mean salary in that specific detailed field for annual salary 
state_df <-  
  state_17 %>% 
  mutate(a_mean = ifelse(is.na(a_mean), mean(a_mean, na.rm = TRUE), a_mean)) %>% 
  mutate(state = tolower(state))    ## To match the case of state names in 2 dataframe 


## Add state salary df.
state_salary <- 
  state_df %>%
  filter(str_detect(occ_code, "15-0000") ) %>% 
  filter(!state %in% c("Puerto Rico","Guam", "Virgin Islands")) %>% 
  group_by(state) %>%
  summarize(abb = st,
            mean_salary = a_mean,
            mean_total = tot_emp,
            mean_job = round(as.numeric(jobs_1000), 2))

## By using map plotly
states_map <- map_data("state")

state_salary$hover <- 
  with(state_salary, paste(
    "Salary: $", round(mean_salary, 2),'<br>',
            "Total:", mean_total, '<br>',
            "DS Jobs per 1000:", mean_job,'<br>'))

# give state boundaries a white border
l <- list(color = toRGB("white"), width = 2)
# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)
```


```{r treemap, message=FALSE, warning=FALSE, include=F}
datascience <- read_csv("./data/ds_500.csv") %>% 
  filter(!is.na(position))

pattern_bg = c("[Cc]omputer [Ss]cience | \\bC\\.?S\\b | [Mm]achine [Ll]earning | \\bM\\.?L\\b", 
                 "[Ss]tatistic", 
                 "[Mm]ath", 
                 "[Qq]uantitative", 
                 "[Ee]conomic", 
                 "[Bb]iolog", 
                 "[Bb]iostatis", 
                 "[Dd]ata [Ss]cience | \\bD\\.?S\\b", 
                 "[Cc]hemical [Ee]ngineering")
name_bg = c("computer science", 
          "statistics", 
          "mathematics", 
          "quantitative", 
          "economics", 
          "biology", 
          "biostatistics", 
          "data science", 
          "engineer")

bg_freq = data.frame(
  background = pattern_bg, 
  index = name_bg, 
  freq_total = rep(0, length(pattern_bg)), 
  fortune500 = rep(0, length(pattern_bg)), 
  nonfortune500 = rep(0, length(pattern_bg)) 
)

for (i in c(1:length(pattern_bg))) {
  bg_freq$freq_total[i] = sum(str_detect(datascience$description, as.character(bg_freq$background[i])))
  bg_freq$fortune500[i] = sum(str_detect(datascience$description[which(datascience$flag == 1)], as.character(bg_freq$background[i])))
  bg_freq$nonfortune500[i] = sum(str_detect(datascience$description[which(datascience$flag == 0)], as.character(bg_freq$background[i])))
}

n_top500 = sum(datascience$flag == 1)
n_nontop500 = sum(datascience$flag == 0)
bg_freq = 
  bg_freq %>% 
  gather(key = subgroup, value = freq, fortune500:nonfortune500) %>% 
  mutate(freq_ratio = ifelse(subgroup == "fortune500", freq/n_top500, freq/n_nontop500)) %>% 
  mutate(subgroup = paste(subgroup, ": n = ", freq, " (out of ", ifelse(subgroup == "fortune500", n_top500, n_nontop500), " job postings, ratio = ", round(freq_ratio*100, digits = 1), "%)", sep = ""))

p = 
treemap(
    bg_freq,
    index = c("index", "subgroup"), 
    vSize = "freq_ratio", 
    vColor = "freq_ratio", 
    type = "value",
    palette = "Blues"
    )
```

```{r read and tidy labor data, message=FALSE, warning=FALSE, include=F}
#read national Occupational Employment Statistics data
read_national_data = function(file_yr) {
  df = 
  read_excel(str_c("data/national_10yr/national_", file_yr, ".xls")) %>% 
  janitor::clean_names() %>% 
  filter(str_detect(occ_code, "0000$")) %>%
  mutate(year = file_yr) %>% 
  mutate(a_mean = as.numeric(a_mean), 
         a_median = as.numeric(a_median),
         tot_emp = as.numeric(tot_emp),
         mean_prse = as.numeric(mean_prse)) %>% 
  select(year, tot_emp, occ_code, occ_title, a_mean, mean_prse, a_median) 
  
  df
}

#aggregate all 10 years' data in one data frame
national_df = map_df(2008:2017, read_national_data) %>% unnest()

#tidy occupation titles
national_df = 
national_df %>% 
  mutate(occ_title = tolower(occ_title)) %>% 
  mutate(occ_title = str_replace(occ_title, 
                                 "computer and mathematical science occupations", 
                                 "computer and mathematical occupations"),
         occ_title = str_replace(occ_title, 
                                 "community and social service occupations", 
                                 "community and social services occupations"),
         occ_title = str_replace(occ_title, 
                                 "healthcare practitioner and technical occupations", 
                                 "healthcare practitioners and technical occupations")) 

```

```{r tools and skills, message=FALSE, warning=FALSE, include=F}
datascience <- read_csv("./data/ds_500.csv")

# Extract tool variable
tool_new = datascience %>% 
  mutate(
    python = ifelse(str_detect(.$description,  c("\\b[Pp][Yy][Tt][Hh][Oo][Nn]\\b")) == TRUE, 1, 0),
    excel = ifelse(str_detect(.$description,  c("\\b[Ee][Xx][Cc][Ee][Ll]\\b")) == TRUE, 1, 0),
    r = ifelse(str_detect(.$description,  c("\\b[Rr]\\b")) == TRUE, 1, 0),
    sql = ifelse(str_detect(.$description,  c("\\b[Ss][Qq][Ll]\\b")) == TRUE, 1, 0),
    java = ifelse(str_detect(.$description,  c("\\b[Jj][Aa][Vv][Aa]\\b")) == TRUE, 1, 0),
    tableau = ifelse(str_detect(.$description,  c("\\b[Tt][Aa][Bb][Ll][Ee][Aa][Uu]\\b")) == TRUE, 1, 0),
    sas = ifelse(str_detect(.$description,  c("\\b[Ss][Aa][Ss]\\b")) == TRUE, 1, 0),
    matlab =  ifelse(str_detect(.$description,  c("\\b[Mm][Aa][Tt][Ll][Aa][Bb]\\b")) == TRUE, 1, 0),
    c = ifelse(str_detect(.$description,  c("\\b[Cc]\\b")) == TRUE, 1, 0),
    perl = ifelse(str_detect(.$description,  c("\\b[Pp][Ee][Rr][Ll]\\b")) == TRUE, 1, 0), 
    scala = ifelse(str_detect(.$description,  c("\\b[Ss][Cc][Aa][Ll][Aa]\\b")) == TRUE, 1, 0), 
    spark = ifelse(str_detect(.$description,  c("\\b[Ss][Pp][Aa][Rr][Kk]\\b")) == TRUE, 1, 0), 
    hadoop = ifelse(str_detect(.$description,  c("\\b[Hh][Aa][Dd][Oo][Oo][Pp]\\b")) == TRUE, 1, 0), 
    aws = ifelse(str_detect(.$description,  c("\\b[Aa][Ww][Ss]\\b")) == TRUE, 1, 0),
    hive = ifelse(str_detect(.$description,  c("\\b[Hh][Ii][Vv][Ee]\\b")) == TRUE, 1, 0),
    tensorflow = ifelse(str_detect(.$description,  c("\\b[Tt][Ee][Nn][Ss][Oo][Rr][Ff][Ll][Oo][Ww]\\b")) == TRUE, 1, 0),
    linux = ifelse(str_detect(.$description,  c("\\b[Ll][Ii][Nn][Uu][Xx]\\b")) == TRUE, 1, 0)
    )

# Extract skill variable
skill_new = datascience %>%
  mutate(
    machine_learning = ifelse(str_detect(.$description,  c("[Mm]achine [Ll]earning")) == TRUE, 1, 0),
    deep_learning = ifelse(str_detect(.$description,  c("[Dd]eep [Ll]earning")) == TRUE, 1, 0),
    # Data Manipulation & Analysis
    data_mani_ana = ifelse(str_detect(.$description,  c("[Dd]ata [Aa]nalysis|[Dd]ata [Mm]anipulation|[Dd]ata [Mm]anagement|[Dd]ata [Ee]valuation|[Ss]tatistical [Aa]nalysis|[Rr]egression")) == TRUE, 1, 0),
    # data visualization
    data_visul = ifelse(str_detect(.$description,  c("[Dd]ata [Vv]isualization")) == TRUE, 1, 0),
    data_mining = ifelse(str_detect(.$description,  c("[Dd]ata [Mm]ining")) == TRUE, 1, 0),
    modeling = ifelse(str_detect(.$description,  c("[Mm]odeling")) == TRUE, 1, 0),
    # include machine learning optimization, data optimization, mathematical optimization???
    optimization = ifelse(str_detect(.$description,  c("[Oo]ptimization")) == TRUE, 1, 0),
    # interpersonal skills
    interpersonal = ifelse(str_detect(.$description,  c("[Ii]nterpersonal [Ss]kill|[Cc]ommunication|[Ll]istening [Ss]kill|[Tt]eam [Ww]orking|[Nn]egotiation|[Ee]motional [Ii]ntelligence|[Cc]onflict [Rr]esolution|[Pp]roblem [Ss]olving|[Dd]ecision [Mm]aking")) == TRUE, 1, 0),
    # artifical intelligence
    arti_inte = ifelse(str_detect(.$description,  c("\\bAI\\b|[Nn]eural [Nn]etwork")) == TRUE, 1, 0),
    writing = ifelse(str_detect(.$description,  c("[Ww]riting")) == TRUE, 1, 0)
  )
```

Column {data-width=550}
-----------------------------------------------------------------------

### {data-height=600}

```{r}
plot_geo(state_salary, locationmode = 'USA-states') %>%
  add_trace(
    z = ~ mean_salary, text = ~hover, locations = ~ abb,
    color = ~ mean_salary, colors = 'Oranges'
  ) %>%
  colorbar(title = "$:USD") %>%
  layout(
    title = '2017 US Data Science jobs info by State<br>Source: <a href="https://www.bls.gov/oes/tables.htm">BLS</a>',
    titlefont = 8,
    geo = g, 
    legend = list(x = 0.1, y = 0.1, orientation = 'h')
  )
```

### {data-height=400, .tabset}

```{r}
d3tree(p, rootname = "Related Background")
```

Column {data-width=450, .tabset}
-----------------------------------------------------------------------

### Job Vacancy

```{r plotting increment rate}

#Compare the increment rate of total employment in our selected occupational fields
national_df %>% 
  group_by(occ_code) %>% 
  arrange(year) %>% 
  mutate(increment = ifelse(year == 2008 ,0, diff(tot_emp, 1,1))) %>% 
  mutate(increment_p = increment / tot_emp) %>%
  mutate(hover = paste(round(increment_p*100, 2), "% Increment",'<br>',
                        "Total Employment:", round(tot_emp,2) ,'<br>',
                        "Median Salary: $", round(a_median, 2))) %>% 
  filter(occ_code %in% c("13-0000",
                         "15-0000",
                         "17-0000",
                         "19-0000",
                         "29-0000",
                         "41-0000",
                         "00-0000"),
         year != "2008") %>%
  plot_ly(x = ~year, y = ~increment_p*100, color = ~occ_title, 
            type = 'scatter', mode = 'lines+markers', text = ~hover)%>% 
  layout(legend = list(x = 0.7,y = 0.4),
         title = "Employment increment rate by occupations in the U.S.",
         xaxis = list(title = "Year"),
         yaxis = list(title = "Annual percentage increase(%) in total empolyment"))

```

### Annual Salary Change

```{r 10 yr salary trend across occupations, warning=FALSE, message=FALSE}
#plotting the 10-yr trend of median annual salary across all major fields.
national_df %>%
  group_by(occ_code) %>% 
  mutate(hover = paste(occ_title, '<br>',
                       "Year:", year, '<br>',
                      "Median Salary: $", round(a_median, 2))) %>% 
  plot_ly(x = ~year, y = ~a_median, color = ~occ_title,
         type = 'scatter', mode = 'lines+markers', text = ~hover) %>% 
  layout(showlegend = FALSE,
         title = "10-year trend of median annual salary<br>by occupations in the U.S.",
         xaxis = list(title = "Year"),
         yaxis = list(title = "Mean Annual Salary($)"))
 
```

### Required Tools

```{r}
ax <- list(
  title = ""
)

tool_new %>% 
  gather(key = tool, value = value, python:linux) %>%
  filter(value == 1) %>% 
  count(flag, tool) %>% 
  mutate(
    flag = as.factor(flag),
    flag = ifelse(flag == 1, "top500", "non_top500"),
    tool = str_to_title(tool),
    tool = recode(tool, "C" = "C/C++", "Sql" = "SQL", "Sas" = "SAS", "Aws" = "AWS")
         ) %>% 
  spread(key = flag, value = n) %>% 
  mutate(sum = non_top500 + top500,
         tool = fct_reorder(tool, sum)) %>% 
  plot_ly(.) %>% 
  add_trace(y = ~tool, x = ~top500, type = "bar", name = "Fortune 500", marker = list(color = 'blue-teal')) %>%
  add_trace(y = ~tool, x = ~non_top500, type = "bar", name = "Non-fortune 500", marker = list(color = 'lightblue')) %>%
  layout(
    title = "Fortune 500 v.s. Non-fortune 500: Most required tools",
    xaxis = list(title = 'Count'), barmode = 'stack',
    yaxis = ax
    )
```

### Required Skills

```{r}
skill_new %>% 
  gather(key = skill, value = value, machine_learning:writing) %>%
  filter(value == 1) %>% 
  count(flag, skill) %>% 
  mutate(
    flag = as.factor(flag),
    flag = ifelse(flag == 1, "top500", "non_top500")
         ) %>% 
  spread(key = flag, value = n) %>% 
  mutate(sum = non_top500 + top500) %>%
  cbind(skills = c("Artifiical Intelligence", "Data Manipulation & Analysis", "Data Mining", "Data Visualization", "Deep Learning", "Interpersonal Skills", "Machine Learning", "Modeling", "Optimization", "Writing Skills")) %>% 
  select(skills, 2, 3, 4) %>% 
  mutate(skills = fct_reorder(skills, sum)) %>% 
  plot_ly(.) %>% 
  add_trace(y = ~skills, x = ~top500, type = "bar", name = "Fortune 500", width = .6, marker = list(color = 'lightseagreen')) %>%
  add_trace(y = ~skills, x = ~non_top500, type = "bar", name = "Non-fortune 500", width = .6, marker = list(color = ' lightgreen')) %>%
  layout(
    title = "Fortune 500 v.s. Non-fortune 500: Most required skills",
    yaxis = ax,
    xaxis = list(title = 'Count'), barmode = 'stack',
    bargap = 0.05
    ) 
```